### ISSUE TITLE
Please create tags in GitHub for releases

### ISSUE THREAD

**Issue by robbat2** [puppetlabs/semantic_puppet#10]
per $SUBJ, please include tags in github, so that releases on rubygems can traced back to specific code in github.

**Comment by scotje** [comment]
Will do. I thought we generally used the rake task for publishing which does it automatically, so I'm slightly surprised it didn't happen for the first couple.

**Comment by robbat2** [comment]
Still no tags here :-(

**Comment by robbat2** [comment]
As a thought, maybe you didn't push the tags from your local repo?

**Comment by scotje** [comment]
Sorry, I meant that future releases would be tagged. I'll try to figure out what the previously released tags should be and push those up.
