### ISSUE TITLE
SyntaxError with version 0.1.4

### ISSUE THREAD

**Issue by degano** [puppetlabs/semantic_puppet#20]
Hi!
When installing 'r10k' through gem, 'semantic_puppet' version 0.1.4 is installed with it.
However when launching r10k an error is raised, which seems to be coming from semantic_puppet:
```
r10k 
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': /usr/lib/ruby/gems/1.8/gems/semantic_puppet-0.1.4/lib/semantic_puppet/version.rb:21: odd number list for Hash (SyntaxError)
...rsion identifier") % {version: ver}
```
When forcing version 0.1.1 for semantic_puppet the error is not raised.
The relevant environment is the following:
OS: RHEL 6.8
Ruby: ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]

**Comment by degano** [comment]
Also, I see on the first page that Ruby 1.8.7 is nominally deprecated. However the version 0.1.4 is still installed as dependency when installing r10k.

**Comment by tomasquith** [comment]
Thanks for this, this saved me some pain!

**Comment by joshcooper** [comment]
This should be fixed in https://github.com/puppetlabs/semantic_puppet/pull/30 /cc @scotje

**Comment by scotje** [comment]
Version 1.0.2 has been released which removes the string externalization syntax which seemed to be the source of this issue.
