### ISSUE TITLE
Consider fleshing out or dropping i18n support

### ISSUE THREAD

**Issue by rnelson0** [puppetlabs/semantic_puppet#22]
In [this commit](https://github.com/puppetlabs/semantic_puppet/commit/85bf8fc6087a0fdbc40a0a70f170877bdd576788), i18n locale support for translations was enabled. It does not appear that any locale info was added, as well as the .pot file being excluded in .gitignore. This adds a dependency on gettext-setup which has its own dependencies, which today caused issues when a new gettext release dropped support for certain versions of ruby.

Unless I misunderstand how gettext-setup works (which is quite possible!) in the current implementation this simply adds a dependency but provides no benefit. Can this either be enabled if it will be used, or removed to eliminate the dependency if it will not?

I do not have permission to see [CODEMGMT-725](https://tickets.puppetlabs.com/browse/CODEMGMT-725) to see why gettext-setup was originally chosen.

**Comment by scotje** [comment]
See #30
