### ISSUE TITLE
Provide a new release

### ISSUE THREAD

**Issue by ekohl** [puppetlabs/semantic_puppet#45]
Over a year ago https://github.com/puppetlabs/semantic_puppet/pull/40 was merged, but there's no release yet. It'd be great if one was made so I no longer need to use a git version.

**Comment by ekohl** [comment]
I'd still like to see this.

**Comment by mhashizume** [comment]
Hi @ekohl , I'll work on pushing this out today.

**Comment by ekohl** [comment]
Thanks @mhashizume! Saves me from having to use the git version.
